# Step 1
FROM node:16-alpine as build-step

WORKDIR /code

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY . .

RUN npm run build

# Stage 2
FROM nginx:1.17.1-alpine
COPY --from=build-step /code/build /usr/share/nginx/html
