version: '3'
services:          
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.prod  
        container_name: react-prod
        ports:
            - "3000:80"