version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: npm run start
        container_name: react-dev
        ports:
            - "3000:80"
        volumes:
            - ./:/code